package com.awrank.web.model.constant;

/**
 * User: a_polyakov
 */
public enum EMessageConst {
    ERROR,
    ERROR_ACCESS,
    ERROR_NETWORK,

    MISSING_OBJECT_ID,

    OBJECT_NOT_UNIQUE,

    MISSING_DICTIONARY_LANGUAGE,
    MISSING_DICTIONARY_CODE,
    MISSING_DICTIONARY_TEXT,

    SECRET_QUESTION_FAVORITE_NUMBER,
    SECRET_QUESTION_OTHER;
}
