package com.awrank.web.model.enums;

/**
 * Constants which define messages keys.
 *
 * @author Alex Polyakov
 */
public enum Message {
	ERROR,
	ERROR_ACCESS,
	ERROR_NETWORK,

	MISSING_OBJECT_ID,

	OBJECT_NOT_UNIQUE,

	MISSING_DICTIONARY_LANGUAGE,
	MISSING_DICTIONARY_CODE,
	MISSING_DICTIONARY_TEXT,

	SECRET_QUESTION_FAVORITE_NUMBER,
	SECRET_QUESTION_OTHER,

	ENTRY_POINT_BY_EMAIL_NOT_FOUND,
	ENTRY_POINT_WRONG_CURRENT_PASSWORD;
}
