package com.awrank.web.model.enums;

/**
 * Constants which define messages keys.
 *
 * @author Alex Polyakov
 */
public enum Message {
	ERROR,
	ERROR_ACCESS,
	ERROR_NETWORK,

	MISSING_OBJECT_ID,

	OBJECT_NOT_UNIQUE,

	MISSING_DICTIONARY_LANGUAGE,
	MISSING_DICTIONARY_CODE,
	MISSING_DICTIONARY_TEXT,

	SECRET_QUESTION_FAVORITE_NUMBER,
	SECRET_QUESTION_OTHER,

	ENTRY_POINT_BY_EMAIL_NOT_FOUND,
	ENTRY_POINT_WRONG_CURRENT_PASSWORD,
    ENTRY_POINT_NOT_FOUND_BY_UID,

	// email
	EMAIL_ALREADY_EXISTS,

	// social
	SOCIAL_NETWORK_EMAIL_NOT_PROVIDED,
	SOCIAL_NEGATIVE_RESPONSE_RECEIVED,
	SOCIAL_INVALID_GOOGLE_STATE_PARAM_VALUE,
	SOCIAL_MISSING_GOOGLE_STATE_PARAM,
	SOCIAL_REQUEST_ACCESS_TOKEN_FAILED,
	SOCIAL_REQUEST_USER_PROFILE_FAILED,
	SOCIAL_NO_AUTH_ACTION_SPECIFIED,
	SOCIAL_ACCESS_TOKEN_IS_NULL,
	SOCIAL_AUTH_CODE_IS_NULL
}
