package com.awrank.web.model.enums;

/**
 * Constants which define messages keys.
 *
 * @author Alex Polyakov
 * @author Andrew Stoyaltsev
 * @author Olga Korokhina
 */
public enum Message {

	ERROR,
	ERROR_ACCESS,
	ERROR_NETWORK,

	MISSING_OBJECT_ID,

	OBJECT_NOT_UNIQUE,

	MISSING_DICTIONARY_LANGUAGE,
	MISSING_DICTIONARY_CODE,
	MISSING_DICTIONARY_TEXT,

	SECRET_QUESTION_FIRST_PET,
	SECRET_QUESTION_MOTHERS_MAIDEN_NAME,
	SECRET_QUESTION_FAVOURITE_DISH,
	SECRET_QUESTION_UNFORGETTABLE_EVENT,

	ENTRY_POINT_BY_EMAIL_NOT_FOUND,
	ENTRY_POINT_WRONG_CURRENT_PASSWORD,
    ENTRY_POINT_NOT_FOUND_BY_UID,

	// email
	EMAIL_ALREADY_EXISTS,

	// social
	SOCIAL_NETWORK_EMAIL_NOT_PROVIDED,
	SOCIAL_NEGATIVE_RESPONSE_RECEIVED,
	SOCIAL_INVALID_GOOGLE_STATE_PARAM_VALUE,
	SOCIAL_MISSING_GOOGLE_STATE_PARAM,
	SOCIAL_REQUEST_ACCESS_TOKEN_FAILED,
	SOCIAL_REQUEST_USER_PROFILE_FAILED,
	SOCIAL_NO_AUTH_ACTION_SPECIFIED,
	SOCIAL_ACCESS_TOKEN_IS_NULL,
	SOCIAL_AUTH_CODE_IS_NULL,
	SOCIAL_LOGIN_FAILED_TITLE,
	SOCIAL_REGISTER_FAILED_TITLE,
	YOU_LOGGED_IN_SUCCESSFULLY,
	YOU_REGISTERED_SUCCESSFULLY_VERIFICATION_EMAIL_SENT,
	YOU_REGISTERED_SUCCESSFULLY,
	REGISTRATION_PASSWORD_AND_CONFIRMATION_ARE_NOT_EQUAL,
	REGISTRATION_YOU_HAVE_TO_AGREE_WITH_TAC,
	REGISTRATION_EMAIL_MALFORMED,
	
	EMAIL_VERIFIED_SUCCESSFULLY,
	EMAIL_NOT_VERIFIED,
	
	PROFILE_FIRST_LAST_NAMES_TOO_SHORT,
	PROFILE_UPDATED_SUCCESSFULLY,
	PROFILE_EMAIL_UPDATED_SUCCESSFULLY,
	
	YOU_HAVE_TO_VERIFY_YOUR_CURRENT_EMAIL_FIRST

}